---
- name: Setup WebServer
  hosts: web01
  become: yes
  tasks:
   - name: Install Apache httpd
     yum:
       name: httpd
       state: present
   - name: Start & Enable Htttpd
     service:
       name: httpd
       state: started
       enabled: yes
